### ISSUE TITLE
Create Curious Edinburgh splash screen

### ISSUE THREAD

**Issue by gmh04** [edina/CuriousEdinburgh2#13]
On start up the Curious Edinburgh splash screen will be displayed.

**Comment by NicolaOsborne** [comment]
And change launch icon.

**Comment by gmh04** [comment]
Some IOS work to be done: https://github.com/remobile/react-native-splashscreen

**Comment by jollopre** [comment]
I have added iOS icons (see commit 8e9d4660a146160170a040b688944e238e5b9936), however I have problems installing react-native-splashscreen. It's best not merging to master until the splashscreen third party is installed, otherwise we get warning messages on iOS devices.

**Comment by jollopre** [comment]
Some people are also having problems to install, see https://github.com/remobile/react-native-splashscreen/issues/18

**Comment by gmh04** [comment]
complete for this milestone
