### ISSUE TITLE
Test - Display tour records on map as markers

### ISSUE THREAD

**Issue by jollopre** [edina/CuriousEdinburgh2#23]
Test are needed for the issue: https://github.com/edina/CuriousEdinburgh2/issues/5

**Comment by jollopre** [comment]
Enzyme utility for react can help us to assert, manipulate, and traverse the React Components' output.

**Comment by jollopre** [comment]
@NicolaOsborne are you sure you want to include test in this milestone? I thought we agree the leave out until we have a functional prototype.

**Comment by NicolaOsborne** [comment]
Hi @jollopre, you are right. This should be moved to a later milestone - I'll do that now.
