### ISSUE TITLE
Need to cache Tour data on client

### ISSUE THREAD

**Issue by gmh04** [edina/CuriousEdinburgh2#24]
We should be caching tour data on client so we are not continually doing requests to the server.  Initially, probably good enough if the cache lasts a session.

Implementation of https://github.com/edina/CuriousEdinburgh2/issues/8 has shown that the JSON requires some parsing (esp HTML parsing of the content.rendered field).  I think it makes sense for this to be done once and the data we store is only what we need (i.e don't store the original payload).

For example, we could store a structure like:

```
{
    {
        id: "tour1",
        description: "some tour blah blah"
    } : [
        {
            title: "myplace"
            description: "blah blah",
            image: "http://curiousedinburgh.org/wp-content/uploads/2016/07/myplace.jpg",
            location: {
                lon: -3.2138,
                lat:  55.9332
            },
        },
        {
            title: "anotherplace",
        ...
    },
    {
        id: "tour2",
        description: "another tour blah blah"
    } : [
   ...
```

The first time the app is started the following steps have to be done.
1. Retrieve all the categories
2. Filter only those that have more than one post, i.e. count property is more than 1.
3. Select History of Science tour as default
4. Retrieve all the posts for History of Science tour.

If the tour is changed at any point, we have to fetch its posts. In addition, we have to cache the posts for any tour previously fetched.

**Comment by NicolaOsborne** [comment]
Caching sounds sensible as long as data requirement isn't huge. For tourists I think lower data usage (in an ideal world - not this iteration - offline mode) would be a substantial perk.

**Comment by NicolaOsborne** [comment]
@jollopre, as discussed, the History of Science Tour should be the default tour please.
