### ISSUE TITLE
Create Tours Page

### ISSUE THREAD

**Issue by gmh04** [edina/CuriousEdinburgh2#4]
A navigation button on the app header on the home page will navigate the user to this screen.  This will list the available tours in the app.

example:

![Alt text](https://raw.githubusercontent.com/edina/CuriousEdinburgh2/fc71fdb22793bccd3602586eacdae3deabc8bcaa/images/tours.png)

**Comment by gmh04** [comment]
@NicolaOsborne maybe want to rethink how this works (perhaps a menu instead).

**Comment by NicolaOsborne** [comment]
@gmh04 I think the team are open to suggestions on this, as long as it's easy to do and you can pick between tours - and create new tours based on similar-to-current API process - that should be fine. Perhaps we can take a look (offline) at some examples of alternative approaches?

**Comment by jollopre** [comment]
The WordPress API does not have an explicit call to retrieve all the categories, i.e. the tours available. We have agreed (George and me) that the first time the app runs, we will retrieve the first 20 categories, i.e. the first 20 tours available at the blog.

**Comment by gmh04** [comment]
TODO: use icon library for menu button instead of  src/assets/menu.png
