### ISSUE TITLE
Tour record popups - iOS

### ISSUE THREAD

**Issue by NicolaOsborne** [edina/CuriousEdinburgh2#50]
iOS:

MapView.Callout appears behind custom markers for markers that are enough close to each other. See issue airbnb/react-native-maps#553 for more details
MapView.Marker.onPress: only works when pressing in the LatLng of the marker
MapView.Marker.onCalloutPress: sometimes is not fired

**Comment by jollopre** [comment]
- Callouts displaying behind markers (latest fix https://github.com/airbnb/react-native-maps/pull/806)
