### ISSUE TITLE
Tour Selection for Android

### ISSUE THREAD

**Issue by NicolaOsborne** [edina/CuriousEdinburgh2#52]
Improve the scale and look of the Tour Selection menu/page for Android

**Comment by gmh04** [comment]
I've improved the scale of the Tour list selected.  Unfortunate I cannot improve the usability of the Picker that comes natively with React Native on android.  There are alternative 3rd party Picker plugins that we can try should the current picker be deemed unacceptable.

**Comment by NicolaOsborne** [comment]
If the scaling is fixed @gmh04, then that should be fine. It was the very small size of the list that was the biggest part of this issue. Might add alternative picker to longer term roadmap.
