### ISSUE TITLE
Tour Record Display Page - View Images

### ISSUE THREAD

**Issue by NicolaOsborne** [edina/CuriousEdinburgh2#53]
Image popups are fine for next phase.

**Comment by gmh04** [comment]
@jollopre I've got the image viewer working for android.  I anticipate this currently will not work for IOS as I had to link this plugin manually, see https://github.com/alwx/react-native-photo-view/issues/16.  I assume it will be a case of doing the IOS equivalent of https://github.com/alwx/react-native-photo-view#user-content-manual-installation.

**Comment by gmh04** [comment]
Problem on IOS, see https://github.com/alwx/react-native-photo-view/issues/44
