### ISSUE TITLE
Tour records popup

### ISSUE THREAD

**Issue by gmh04** [edina/CuriousEdinburgh2#6]
Clicks on a map marker will create a popup displaying the tour record name.  Clicking on popup will navigate the user to the record page.

The marker has to show the tour stop.

**Comment by NicolaOsborne** [comment]
NB: Need to ensure that there is a custom marker showing stop number for each marker. (e.g. stop number 1 has a marker labelled 1, etc.)

**Comment by jollopre** [comment]
We have found the following issues:

- MapView.Marker: The tour stop text appears duplicated, however the tourPlace object has no duplicated tour stop.

- MapView.Callout: Appears behind custom markers, for those markers that are close to each other. See issue https://github.com/airbnb/react-native-maps/issues/553 for more details

- MapView.Marker.onPress: only works at the latLng of the marker

TODO:
link the Callout title to the tourRecord.

**Comment by gmh04** [comment]
for this milestone this is complete
