### ISSUE TITLE
Tour Record details page

### ISSUE THREAD

**Issue by gmh04** [edina/CuriousEdinburgh2#7]
This page display the details of a Tour record. A close button on the header will navigate the user back to where the user came from (either Map of Tour List)

see:

![Alt text](https://raw.githubusercontent.com/edina/CuriousEdinburgh2/fc71fdb22793bccd3602586eacdae3deabc8bcaa/images/record.png)

**Comment by gmh04** [comment]
TODO: 

* some work is need in the styling of the header (esp for smaller screens and IOS)
* show images in popup when clicked
* show videos (note in existing app the video is not shown in popup as images do).

@NicolaOsborne perhaps image popup and videos can be done in next phase?

**Comment by NicolaOsborne** [comment]
Image popups are fine for next phase. 

If video can be shown (and ideally played) in this phase that would be useful.

**Comment by gmh04** [comment]
Header looks good in android, needs tweeking for IOS
