### ISSUE TITLE
Alert messages for network communication

### ISSUE THREAD

**Issue by jollopre** [edina/CuriousEdinburgh2#76]
We have experienced some empty alert messages coming from MapBox API (e.g. 429 status code which means too many request made) due to they don't provide statusText for some http status codes.
In order to give better feedback to the user, we want to create a middleware model (e.g. PromiseErrorHandler) that captures http status, http statusText and the URL requested. Bear in mind that not every attribute can be captured for any request, however at least one of them will be displayed to the user.

**Comment by NicolaOsborne** [comment]
Thanks Jose. Can you suggest the best way to test this?
