### ISSUE TITLE
Route paths might not work

### ISSUE THREAD

**Issue by jollopre** [edina/CuriousEdinburgh2#79]
In order to create the path for a tour, we rely on a third party (e.g. MapBox) and we use the same token api for every device that has the app installed. There are two potential problems: one is security since we are sharing the API key and second is facing http status code 429 (too many requests).

I can think of three options to reduce or eliminate the problem:
- Manually create the paths for a tour and store them in a WordPress custom field.
- Caching a route for a tour from a third party service.
- Using several API keys from different user accounts to call the third party service for solving the route.

**Comment by NicolaOsborne** [comment]
Which of these looks most sensible at the moment? Obtaining third party routings then storing in a WordPress custom field sounds doable (if requiring a little extra manual updating). Is this a sensible way to proceed?

**Comment by jollopre** [comment]
I would go for the first, i.e. manually call to MapBox for each tour and store the route paths on custom_field. Note, this will need our intervention any time a new tour is added in WordPress but after that, any phone would retrieve that field from our WordPress which seems to work smoothy.

**Comment by jollopre** [comment]
It has been decided to hide the alert if any error is arisen. This means it will be fail silently and no path route will be visible for a tour retrieved.
