### ISSUE TITLE
Fix size of Curious Edinburgh logo in header (Android)

### ISSUE THREAD

**Issue by NicolaOsborne** [edina/CuriousEdinburgh2#81]
There appears to be an issue with the sizing of the Curious Edinburgh logo within the header of the app on (some) Android devices. This is visible on the top right hand side of the image below. 

![wrappingissue-20170807](https://user-images.githubusercontent.com/925133/29023444-8fded13c-7b65-11e7-8ad7-bd4762388e2a.png)

**Comment by jollopre** [comment]
@gmh04, could you check whether or not the logo still overlaps the maximum header size for android?
