### ISSUE TITLE
Show image captions when tapped

### ISSUE THREAD

**Issue by NicolaOsborne** [edina/CuriousEdinburgh2#87]
On tour stop pages: when an image is tapped, and is shown full screen, the accompanying caption should be shown.

Jose suggests doing this through regex:

For the images, we currently run a regex to retrieve any content within the attribute src of an img HTML element. We can extend to retrieve the attribute alt, which represents the caption.

In terms of displaying the caption, preference would be for a small semi-transparent overlay, but anything that works and provides sufficient contrast to be readable would be fine.

**Comment by jollopre** [comment]
@NicolaOsborne we have a workable image caption placed at the bottom of the screen. If the text size is greater than the space allocated, i.e. the fixed height. The text becomes scrollable. Let me know if the image below represents what you were thinking:

![simulator screen shot 22 sep 2017 10 43 54](https://user-images.githubusercontent.com/7393044/30738721-e63ba550-9f82-11e7-8def-f0813ed1c169.png)

**Comment by gmh04** [comment]
On android getting com.reactnative.photoview.PhotoView cannot be cast to android.view.ViewGroup, see: https://github.com/alwx/react-native-photo-view/issues/6

**Comment by jollopre** [comment]
Latest commit changes the minimum zoom scale in order to see more details of the image when the ImageViewer is rendered.
