### ISSUE TITLE
Create About page

### ISSUE THREAD

**Issue by gmh04** [edina/CuriousEdinburgh2#9]
see

![Tour Record Page](https://raw.githubusercontent.com/edina/CuriousEdinburgh2/fc71fdb22793bccd3602586eacdae3deabc8bcaa/images/about.png)

**Comment by gmh04** [comment]
Agreed with @NicolaOsborne for the first iteration this page will be a WebView fetched from the WP API.

**Comment by NicolaOsborne** [comment]
For our next release we will want the page to be generated through WP API

**Comment by gmh04** [comment]
We need to think about how we will do this.  The API currently doesn't have the metadata we need - description and image, e.g see http://curiousedinburgh.org/wp-json/wp/v2/categories/4.  The description field is currently being used as a flag to determine whether should tour be visible.

**Comment by gmh04** [comment]
It was requested for the tours to be click-able, so to change the current select tour.  Which should be navigated to after click - map or list?

**Comment by gmh04** [comment]
@NicolaOsborne we discussed changing the the Tour/category last meeting so we can dynamically build the About page. we did this by adding custom fields.  can you tell me which tour you did this to?  I don#t see any change to:

http://curiousedinburgh.org/wp-json/wp/v2/categories/4
http://curiousedinburgh.org/wp-json/wp/v2/categories/21
http://curiousedinburgh.org/wp-json/wp/v2/categories/25

**Comment by gmh04** [comment]
No dynamic Tour details for this milestone.

**Comment by NicolaOsborne** [comment]
I am closing this issue but adding a new low priority version for future roadmap. Also adding a new short item for the snagging - so we can add the new biotech tour to this page.
